repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.1
    hooks:
      - id: golangci-lint
        entry: golangci-lint run
        types: [ go ]
        language: golang
        pass_filenames: false
        stages:
          - push